baseURL = "https://www.silent-cxl.top/"
title = "Silent 的博客"
paginate = 6
theme = "PaperMod"
enableInlineShortcodes = true
enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false
enableEmoji = true
pygmentsUseClasses = true
defaultContentLanguage = "zh"
copyright = "粤ICP备88888888号-1"

[minify]
disableXML = true

[languages.zh]
languageName = "中文"
weight = 1
  [languages.zh.taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"

[[languages.zh.menu.main]]
name = "归档"
url = "archives/"
weight = 5

[[languages.zh.menu.main]]
name = "搜索"
url = "search/"
weight = 10

[[languages.zh.menu.main]]
name = "分类"
url = "categories/"
weight = 15

[[languages.zh.menu.main]]
name = "关于"
url = "about/"
weight = 20

[outputs]
home = [ "HTML", "RSS", "JSON" ]

[params]
env = "production"
description = "Blog 包含 PHP、Golang 等语言，用作记录问题、随笔、学习笔记等，欢迎互相交流"
author = "silent"
defaultTheme = "auto"
ShowShareButtons = true
ShowReadingTime = true
displayFullLangName = true
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = true
ShowRssButtonInSectionTermList = true
comments = true
ShowToc = true
images = [ "papermod-cover.png" ]
  ## 配置 utteranc评论,教程参考 https://utteranc.es/
  [params.utteranc]
  enable = false
  repo = "cxlcxl/comments-for-hugo"
  issueTerm = "pathname"
  theme = "github-light"
  ## 配置 giscus 评论,教程参考 https://giscus.app/zh-CN
  [params.giscus]
  enable = true
  repo = "cxlcxl/comments-for-hugo"
  repoId = "R_kgDOIeSMUw"
  category = "General"
  categoryId = "DIC_kwDOIeSMU84CSrE5"
  mapping = "pathname"
  theme = "light_protanopia"
  lang = "zh-CN"
  crossorigin = "anonymous"

  [params.profileMode]
  enabled = false
  title = "PaperMod"
  imageUrl = "#"
  imageTitle = "my image"

    [[params.profileMode.buttons]]
    name = "Archives"
    url = "archives"

    [[params.profileMode.buttons]]
    name = "Tags"
    url = "tags"

  [params.homeInfoParams]
  Title = "Hi, Hello world!"
  Content = "Blog 包含 PHP、Golang 等语言，用作记录问题、随笔、学习笔记等，欢迎互相交流"

  [[params.socialIcons]]
  name = "github"
  url = "https://github.com/cxlcxl"

  #[[params.socialIcons]]
  #name = "KoFi"
  #url = "https://ko-fi.com/adityatelange"

  [[params.socialIcons]]
  name = "Rss"
  url = "index.xml"

  [params.editPost]
  URL = "https://github.com/cxlcxl/personal-blog/blob/master/content"
  Text = "Suggest Changes"
  appendFilePath = true

  [params.assets]
  disableHLJS = true

[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
noClasses = false

[privacy.vimeo]
disabled = false
simple = true

[privacy.twitter]
disabled = false
enableDNT = true
simple = true

[privacy.instagram]
disabled = false
simple = true

[privacy.youtube]
disabled = false
privacyEnhanced = true

[services.instagram]
disableInlineCSS = true

[services.twitter]
disableInlineCSS = true
