baseURL = "https://www.wtcxl.cn/"
title = "Silent 的博客"
paginate = 5
theme = "PaperMod"
enableInlineShortcodes = true
enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false
enableEmoji = true
pygmentsUseClasses = true
defaultContentLanguage = "zh"

[minify]
disableXML = true

[languages.zh]
languageName = "中文"
weight = 1
  [languages.zh.taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"

#[[languages.zh.menu.main]]
#name = "归档"
#url = "archives"
#weight = 5

[[languages.zh.menu.main]]
name = "标签"
url = "tags/"
weight = 10

[[languages.zh.menu.main]]
name = "分类"
url = "categories/"
weight = 15

[[languages.zh.menu.main]]
name = "About"
url = "about/"
weight = 20

[outputs]
home = [ "HTML", "RSS", "JSON" ]

[params]
env = "production"
description = "Theme PaperMod - https://github.com/adityatelange/hugo-PaperMod"
author = "silent"
defaultTheme = "auto"
ShowShareButtons = true
ShowReadingTime = true
displayFullLangName = true
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = true
ShowRssButtonInSectionTermList = true
ShowToc = true
images = [ "papermod-cover.png" ]

  [params.profileMode]
  enabled = false
  title = "PaperMod"
  imageUrl = "#"
  imageTitle = "my image"

    [[params.profileMode.buttons]]
    name = "Archives"
    url = "archives"

    [[params.profileMode.buttons]]
    name = "Tags"
    url = "tags"

  [params.homeInfoParams]
  Title = "Silent 的博客"
  Content = "一个普通的 PHP、Golang 程序员，欢迎互相交流."

  [[params.socialIcons]]
  name = "github"
  url = "https://github.com/adityatelange/hugo-PaperMod"

  [[params.socialIcons]]
  name = "KoFi"
  url = "https://ko-fi.com/adityatelange"

  [[params.socialIcons]]
  name = "Rss"
  url = "index.xml"

  [params.editPost]
  URL = "https://github.com/adityatelange/hugo-PaperMod/tree/exampleSite/content"
  Text = "Suggest Changes"
  appendFilePath = true

  [params.assets]
  disableHLJS = true

[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
noClasses = false

[privacy.vimeo]
disabled = false
simple = true

[privacy.twitter]
disabled = false
enableDNT = true
simple = true

[privacy.instagram]
disabled = false
simple = true

[privacy.youtube]
disabled = false
privacyEnhanced = true

[services.instagram]
disableInlineCSS = true

[services.twitter]
disableInlineCSS = true
